2023-05-26-icd10cm_billable_hcc_mapper_en
JohnSnowLabs/johnsnowlabs pull request #266
Opened 2023-05-26 13:26 UTC by jsl-models

2023-05-26 13:27 UTC, Ahmetemintek commented
Takes icd10cm code, returns billable and hcc_score.

2023-05-29 13:22 UTC, muhammetsnts requested changes

2023-05-29 13:22 UTC, muhammetsnts commented on docs/_posts/Ahmetemintek/2023-05-26-icd10cm_billable_hcc_mapper_en.md
> +This pretrained model maps ICD-10-CM codes with their corresponding billable and HCC scores. If there is no HCC score for the corresponding icd10cm code, result will be returned as 0.
icd10cm -> ICD-10-CM

2023-05-30 16:02 UTC, muhammetsnts approved these changes

2023-05-30 16:17 UTC, merged