2024-01-16-explain_clinical_doc_oncology_en
JohnSnowLabs/johnsnowlabs pull request #873
Opened 2024-01-16 17:02 UTC by jsl-models

2024-01-16 17:16 UTC, muhammetsnts requested changes

2024-01-16 19:44 UTC, muhammetsnts requested changes

2024-01-16 19:44 UTC, muhammetsnts commented on docs/_posts/bunyamin-polat/2024-01-16-explain_clinical_doc_generic_en.md
> +# Relation Extraction Result
filter O labels in RE results.

2024-01-16 19:44 UTC, muhammetsnts commented on docs/_posts/bunyamin-polat/2024-01-16-explain_clinical_doc_generic_en.md
> +| 10 | B12                                      | TREATMENT  | Planned      |
Check this sentence again, these should be PRESENT

2024-01-16 19:44 UTC, muhammetsnts commented on docs/_posts/bunyamin-polat/2024-01-16-explain_clinical_doc_generic_en.md
> +| 19 | His creatinine                           | TEST       | Absent       |
incorrect

2024-01-16 20:03 UTC, muhammetsnts requested changes

2024-01-16 20:03 UTC, muhammetsnts commented on docs/_posts/bunyamin-polat/2024-01-16-explain_clinical_doc_vop_en.md
> +#NER and Assertion Status Results
shared a request via DM

2024-01-17 07:54 UTC, ahmet-mesut commented on docs/_posts/bunyamin-polat/2024-01-16-explain_clinical_doc_oncology_en.md
> +## Description
Updated according to DM

2024-01-17 14:00 UTC, muhammetsnts requested changes

2024-01-17 14:08 UTC, muhammetsnts requested changes
@akrztrk @bunyamin-polat @SKocer please check here

2024-01-17 14:08 UTC, muhammetsnts commented on docs/_posts/bunyamin-polat/2024-01-17-atc_resolver_pipeline_en.md
> +title: Pipeline for ATC Sentence Entity Resolver
@akrztrk update here

2024-01-17 14:08 UTC, muhammetsnts commented on docs/_posts/bunyamin-polat/2024-01-17-cpt_procedures_measurements_resolver_pipeline_en.md
> +title: Pipeline for CPT Sentence Entity Resolver
@akrztrk update here

2024-01-17 14:08 UTC, muhammetsnts commented on docs/_posts/bunyamin-polat/2024-01-17-cpt_procedures_measurements_resolver_pipeline_en.md
> +This pipeline employs `sbiobert_base_cased_mli` Sentence Bert Embeddings to map diverse `procedures` and `measurements` entities, to Current Procedural Terminology (CPT) codes.
@akrztrk update here

2024-01-17 14:08 UTC, muhammetsnts commented on docs/_posts/bunyamin-polat/2024-01-17-cpt_procedures_measurements_resolver_pipeline_en.md
> +```bash
@akrztrk shorten the results

2024-01-17 14:08 UTC, muhammetsnts commented on docs/_posts/bunyamin-polat/2024-01-17-hcc_resolver_pipeline_en.md
> +title: Pipeline for HCC Sentence Entity Resolver
@akrztrk update here

2024-01-17 14:08 UTC, muhammetsnts commented on docs/_posts/bunyamin-polat/2024-01-17-hcc_resolver_pipeline_en.md
> +This advanced pipeline extracts `PROBLEM` entities from clinical texts and utilizes the `sbiobert_base_cased_mli` Sentence Bert Embeddings to map these entities to their corresponding Hierarchical Co
@akrztrk update here

2024-01-17 14:08 UTC, muhammetsnts commented on docs/_posts/bunyamin-polat/2024-01-17-snomed_findings_resolver_pipeline_en.md
> +title: Pipeline for Snomed Concept, CT version
@bunyamin-polat ~Pipeline for Snomed Concept, CT version`~ : Pipeline for Snomed Concept, Findings Version

2024-01-17 14:38 UTC, ahmet-mesut commented on docs/_posts/bunyamin-polat/2024-01-16-explain_clinical_doc_oncology_en.md
> +## Description
updated

2024-01-17 16:46 UTC, merged