Update 2024-01-17-sbiobertresolve_rxnorm_augmented_en.md
JohnSnowLabs/johnsnowlabs pull request #889
Opened 2024-01-18 14:12 UTC by Ahmetemintek

pipeline is modified.

2024-01-19 09:10 UTC, muhammetsnts approved these changes

2024-02-07 15:39 UTC, muhammetsnts requested changes

2024-02-07 15:39 UTC, muhammetsnts commented on docs/_posts/Ahmetemintek/2024-01-17-sbiobertresolve_rxnorm_augmented_en.md
> +rxnorm_resolver = SentenceEntityResolverModel..pretrained("sbiobertresolve_rxnorm_augmented", "en", "clinical/models")\ \
There is an additional "." before pretrained

2024-02-07 15:39 UTC, muhammetsnts commented on docs/_posts/Ahmetemintek/2024-01-17-sbiobertresolve_rxnorm_augmented_en.md
> -    .setCaseSensitive(False)
case sensitive should be False, you removed this?

2024-02-15 08:51 UTC, closed without merging

2024-02-15 08:56 UTC, akrztrk commented
Combined with other MD card fixes